---
- name: Apache server installed
  hosts: all

  tasks:
  - name: latest Apache version installed
    yum:
      name: {{ pkg }}
      state: latest

  - name: Apache enabled and running
    service:
      name: httpd
      enabled: true
      state: reloaded
