---
- name: Template that fails for the Workflow demo
  hosts: web
  become: yes
  remote_user: ansible 
  tasks:
    - name: Try to install package that doesn't exist
      yum:
        name: htptd
        state: present
      tags:
        - stop
    - name: Rollback failed install
      yum:
        name: httpd
        state: present
      tags:
        - go
